import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { primitives } from "./tokens";
import { themes } from "./themes";
import { validateTokens } from "./validate";

const currentDir = __dirname;
const packageRoot = resolve(currentDir, "..");

async function writeJson(path: string, data: unknown) {
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, `${JSON.stringify(data, null, 2)}\n`);
}

function dartMap(value: unknown): string {
  return JSON.stringify(value, null, 2)
    .replace(/"([^"]+)":/g, "'$1':")
    .replace(/"/g, "'");
}

async function main() {
  validateTokens();

  await writeJson(resolve(packageRoot, "dist/json/primitives.json"), primitives);
  await writeJson(resolve(packageRoot, "dist/json/themes.json"), themes);

  await mkdir(resolve(packageRoot, "dist/flutter"), { recursive: true });
  await writeFile(
    resolve(packageRoot, "dist/flutter/nativesmart_tokens.g.dart"),
    [
      "// Generated by @nativesmart/tokens. Do not edit by hand.",
      "const nativesmartPrimitives = " + dartMap(primitives) + ";",
      "const nativesmartThemes = " + dartMap(themes) + ";",
      ""
    ].join("\n")
  );

  await mkdir(resolve(packageRoot, "dist/react-native"), { recursive: true });
  await writeFile(
    resolve(packageRoot, "dist/react-native/tokens.ts"),
    [
      "// Generated by @nativesmart/tokens. Do not edit by hand.",
      `export const primitives = ${JSON.stringify(primitives, null, 2)} as const;`,
      `export const themes = ${JSON.stringify(themes, null, 2)} as const;`,
      ""
    ].join("\n")
  );
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
